import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { Link, useLocation, useParams } from "wouter";
import { ArrowLeft, Download, FileText, Loader2, LockKeyhole, MessageSquare, Paperclip, Pencil, Pin, Plus, RefreshCw, Send, Trash2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast";
import { getErrorMessage } from "@/lib/api-error";
import { createForumPost, createForumReply, deleteForumDraftAttachment, deleteForumPost, deleteForumReply, editForumPost, editForumReply, forumAcceptedTypes, forumAttachmentUrl, forumKeys, forumLimits, getForumPost, listForumPosts, moderateForumPost, uploadForumAttachment, type ForumAttachment, type ForumPost, type ForumReply } from "@/lib/forum-api";

type Translate = (cn: string, en: string) => string;
function useForumText() { const { i18n } = useTranslation(); const zh = i18n.language.startsWith("zh"); return { tr: ((cn, en) => zh ? cn : en) as Translate, zh }; }
function Attachments({ attachments, tr }: { attachments: ForumAttachment[]; tr: Translate }) {
  if (!attachments.length) return null;
  return <div className="grid min-w-0 gap-3 sm:grid-cols-2">{attachments.map((attachment) => <div key={attachment.id} className="min-w-0 rounded-md border border-border/60 bg-muted/10 p-3">
    {attachment.mimeType.startsWith("image/") && <a href={forumAttachmentUrl(attachment)} target="_blank" rel="noopener noreferrer" className="mb-3 block"><img src={forumAttachmentUrl(attachment)} alt={attachment.fileName} loading="lazy" className="max-h-72 w-full rounded object-contain" /></a>}
    <a href={forumAttachmentUrl(attachment, true)} className="flex min-w-0 items-start gap-2 text-sm text-primary hover:underline" download><Download className="mt-0.5 h-4 w-4 shrink-0" /><span className="min-w-0 break-all">{attachment.fileName}</span></a>
    <p className="mt-1 text-xs text-muted-foreground">{(attachment.size / 1024).toFixed(1)} KiB · {tr("登录后可查看", "Members only")}</p>
  </div>)}</div>;
}
function QueryFailure({ error, retry, tr }: { error: unknown; retry: () => void; tr: Translate }) {
  return <div role="alert" className="space-y-3 rounded-md border border-destructive/40 bg-destructive/5 p-4"><p className="break-words text-sm">{getErrorMessage(error)}</p><Button variant="outline" onClick={retry}><RefreshCw className="mr-2 h-4 w-4" />{tr("重新加载", "Retry")}</Button></div>;
}
function Pagination({ page, pageSize, total, onChange, pending, tr }: { page: number; pageSize: number; total: number; onChange: (page: number) => void; pending: boolean; tr: Translate }) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground"><span>{tr(`第 ${page} / ${pages} 页，共 ${total} 条`, `Page ${page} / ${pages} · ${total} total`)}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={pending || page <= 1} onClick={() => onChange(page - 1)}>{tr("上一页", "Previous")}</Button><Button variant="outline" size="sm" disabled={pending || page >= pages} onClick={() => onChange(page + 1)}>{tr("下一页", "Next")}</Button></div></div>;
}
function ForumComposer({ edit, close, completed, tr }: { edit?: ForumPost; close: () => void; completed: (post: ForumPost) => void; tr: Translate }) {
  const [title, setTitle] = useState(edit?.title ?? ""); const [body, setBody] = useState(edit?.body ?? "");
  const [attachments, setAttachments] = useState<ForumAttachment[]>([]); const [upload, setUpload] = useState<{ name: string; percent: number } | null>(null);
  const [removing, setRemoving] = useState(false); const [error, setError] = useState<string | null>(null); const fileInput = useRef<HTMLInputElement>(null); const busyRef = useRef(false);
  const mutation = useMutation({ mutationFn: () => edit ? editForumPost(edit.id, { title, body, version: edit.version }) : createForumPost({ title, body, attachmentIds: attachments.map((attachment) => attachment.id) }), onSuccess: completed, onError: (cause) => setError(getErrorMessage(cause)) });
  const busy = Boolean(upload) || removing || mutation.isPending;
  async function filesSelected(files: File[]) {
    if (busyRef.current || busy) return; busyRef.current = true; setError(null);
    let count = attachments.length;
    try {
      for (const file of files) {
        if (count >= forumLimits.attachmentsMax) { setError(tr("每篇帖子最多上传 6 个附件。", "A post can contain up to 6 attachments.")); break; }
        setUpload({ name: file.name, percent: 0 });
        try { const attachment = await uploadForumAttachment(file, (percent) => setUpload({ name: file.name, percent })); setAttachments((current) => [...current, attachment]); count++; }
        catch (cause) { setError(getErrorMessage(cause)); break; }
      }
    } finally { setUpload(null); busyRef.current = false; if (fileInput.current) fileInput.current.value = ""; }
  }
  async function remove(attachment: ForumAttachment) { setRemoving(true); setError(null); try { await deleteForumDraftAttachment(attachment.id); setAttachments((current) => current.filter((item) => item.id !== attachment.id)); } catch (cause) { setError(getErrorMessage(cause)); } finally { setRemoving(false); } }
  async function cancel() {
    if (busy || busyRef.current) return;
    if (!attachments.length) { close(); return; }
    busyRef.current = true; setRemoving(true); setError(null);
    try {
      const results = await Promise.allSettled(attachments.map((attachment) => deleteForumDraftAttachment(attachment.id)));
      const retained = attachments.filter((_, index) => results[index].status === "rejected");
      setAttachments(retained);
      if (retained.length) setError(tr("部分草稿附件移除失败，已保留在此处。请重试取消或单独移除；未发布附件会在 24 小时后过期。", "Some draft attachments could not be removed and are retained here. Retry cancel or remove them individually; unpublished attachments expire after 24 hours."));
      else close();
    } finally { busyRef.current = false; setRemoving(false); }
  }
  return <Card className="min-w-0 border-primary/30"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{edit ? tr("编辑帖子", "Edit post") : tr("发布帖子", "Create a post")}</CardTitle><Button variant="ghost" size="icon" aria-label={tr("关闭编辑器", "Close editor")} disabled={busy} onClick={() => { void cancel(); }}><X className="h-4 w-4" /></Button></div><CardDescription>{tr("以本人身份发布。支持图片、PDF 和 TXT；每个文件不超过 5 MiB，最多 6 个。", "Post as yourself. Images, PDF and TXT are supported: up to 5 MiB each, 6 attachments per post.")}</CardDescription></CardHeader>
    <CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!busy && !busyRef.current && title.trim() && (body.trim() || (edit ? edit.attachments.length : attachments.length))) { setError(null); mutation.mutate(); } }}>
      <div className="space-y-2"><Label htmlFor="forum-title">{tr("标题", "Title")}</Label><Input id="forum-title" value={title} disabled={busy} maxLength={forumLimits.titleMax} onChange={(event) => setTitle(event.target.value)} placeholder={tr("这次想分享什么？", "What would you like to share?")} required /><p className="text-right text-xs text-muted-foreground">{title.length} / {forumLimits.titleMax}</p></div>
      <div className="space-y-2"><Label htmlFor="forum-body">{tr("内容", "Content")}</Label><Textarea id="forum-body" rows={7} value={body} disabled={busy} maxLength={forumLimits.bodyMax} onChange={(event) => setBody(event.target.value)} className="break-words" placeholder={tr("分享战斗、攻略、生活或想法……", "Share battles, guides, stories or ideas…")} /><p className="text-right text-xs text-muted-foreground">{body.length} / {forumLimits.bodyMax}</p></div>
      {!edit && <div className="space-y-3"><input ref={fileInput} id="forum-file" type="file" multiple accept={forumAcceptedTypes.join(",")} className="sr-only" disabled={busy || attachments.length >= forumLimits.attachmentsMax} onChange={(event) => { void filesSelected(Array.from(event.target.files ?? [])); }} />
        <Button type="button" variant="outline" disabled={busy || attachments.length >= forumLimits.attachmentsMax} onClick={() => fileInput.current?.click()}><Paperclip className="mr-2 h-4 w-4" />{tr("上传图片 / 文件", "Upload images / files")} ({attachments.length}/6)</Button>
        {upload && <div role="status" className="space-y-1"><p className="break-all text-sm">{tr("上传中", "Uploading")} · {upload.name} · {upload.percent}%</p><div className="h-1.5 overflow-hidden rounded bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${upload.percent}%` }} /></div></div>}
        <div className="grid gap-2 sm:grid-cols-2">{attachments.map((attachment) => <div key={attachment.id} className="flex min-w-0 items-start gap-2 rounded-md border border-border p-2">{attachment.mimeType.startsWith("image/") ? <img src={forumAttachmentUrl(attachment)} alt="" className="h-12 w-12 shrink-0 rounded object-cover" /> : <FileText className="h-8 w-8 shrink-0 text-muted-foreground" />}<div className="min-w-0 flex-1 break-all text-xs">{attachment.fileName}<p className="text-muted-foreground">{(attachment.size / 1024).toFixed(1)} KiB</p></div><Button type="button" size="icon" variant="ghost" className="shrink-0" disabled={busy} aria-label={tr(`移除 ${attachment.fileName}`, `Remove ${attachment.fileName}`)} onClick={() => { void remove(attachment); }}><X className="h-4 w-4" /></Button></div>)}</div>
      </div>}
      {edit && edit.attachments.length > 0 && <p className="text-xs text-muted-foreground">{tr("原有附件保留；编辑不会更改附件。", "Existing attachments are retained when editing.")}</p>}
      {error && <p role="alert" className="break-words text-sm text-destructive">{error}</p>}
      <div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => { void cancel(); }}>{tr("取消", "Cancel")}</Button><Button type="submit" disabled={busy || !title.trim() || (!body.trim() && (edit ? edit.attachments.length === 0 : attachments.length === 0))}>{mutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{edit ? tr("保存修改", "Save changes") : tr("发布", "Publish")}</Button></div>
    </form></CardContent>
  </Card>;
}

export function Forum() {
  const { tr, zh } = useForumText(); const params = useParams<{ id?: string }>(); const postId = Number(params.id); const isDetail = params.id !== undefined;
  const [, setLocation] = useLocation(); const queryClient = useQueryClient(); const { toast } = useToast();
  const [queryInput, setQueryInput] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [replyPage, setReplyPage] = useState(1);
  const [composer, setComposer] = useState<"new" | ForumPost | null>(null); const [replyBody, setReplyBody] = useState(""); const [editingReply, setEditingReply] = useState<ForumReply | null>(null);
  const [confirmation, setConfirmation] = useState<{ kind: "post" | "reply"; id: number } | null>(null); const [operationError, setOperationError] = useState<string | null>(null);
  const list = useQuery({ queryKey: forumKeys.list(query, page), queryFn: ({ signal }) => listForumPosts(query, page, signal), enabled: !isDetail });
  const detail = useQuery({ queryKey: forumKeys.detail(postId, replyPage), queryFn: ({ signal }) => getForumPost(postId, replyPage, signal), enabled: isDetail && Number.isSafeInteger(postId) && postId > 0 });
  useEffect(() => { setComposer(null); setReplyBody(""); setEditingReply(null); setReplyPage(1); setOperationError(null); setConfirmation(null); }, [params.id]);
  useEffect(() => { if (list.data) { const last = Math.max(1, Math.ceil(list.data.total / list.data.pageSize)); if (page > last) setPage(last); } }, [list.data, page]);
  useEffect(() => { if (detail.data) { const last = Math.max(1, Math.ceil(detail.data.replyTotal / detail.data.replyPageSize)); if (replyPage > last) setReplyPage(last); } }, [detail.data, replyPage]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: forumKeys.all });
  const reply = useMutation({ mutationFn: () => editingReply ? editForumReply(editingReply.id, replyBody, editingReply.version) : createForumReply(postId, replyBody), onSuccess: async () => { if (!editingReply && detail.data) setReplyPage(Math.max(1, Math.ceil((detail.data.replyTotal + 1) / detail.data.replyPageSize))); setReplyBody(""); setEditingReply(null); setOperationError(null); await refresh(); toast({ title: tr("回复已保存", "Reply saved") }); }, onError: (cause) => { setOperationError(getErrorMessage(cause)); void refresh(); } });
  const remove = useMutation({ mutationFn: (target: { kind: "post" | "reply"; id: number }) => target.kind === "post" ? deleteForumPost(target.id) : deleteForumReply(target.id), onSuccess: async (_, target) => { setConfirmation(null); setOperationError(null); if (target.kind === "post") setLocation("/forum"); else if (editingReply?.id === target.id) { setEditingReply(null); setReplyBody(""); } await refresh(); toast({ title: tr("内容已删除", "Content deleted") }); }, onError: (cause) => setOperationError(getErrorMessage(cause)) });
  const moderate = useMutation({ mutationFn: (change: { pinned?: boolean; locked?: boolean }) => moderateForumPost(postId, { ...change, version: detail.data!.post.version }), onSuccess: async () => { setOperationError(null); setComposer(null); await refresh(); }, onError: (cause) => { setOperationError(getErrorMessage(cause)); void refresh(); } });
  const busy = reply.isPending || remove.isPending || moderate.isPending;
  const post = detail.data?.post;
  const date = (value: string) => new Date(value).toLocaleString(zh ? "zh-CN" : "en-GB");
  const completed = async (saved: ForumPost) => { setComposer(null); await refresh(); setLocation(`/forum/${saved.id}`); toast({ title: tr("帖子已保存", "Post saved") }); };
  const badges = (item: ForumPost) => <>{item.pinned && <Badge variant="outline" className="border-primary/40 text-primary"><Pin className="mr-1 h-3 w-3" />{tr("置顶", "Pinned")}</Badge>}{item.locked && <Badge variant="secondary"><LockKeyhole className="mr-1 h-3 w-3" />{tr("已锁定", "Locked")}</Badge>}</>;
  return <div className="min-w-0 space-y-5 p-4 sm:p-6" data-testid="forum-page">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h1 className="flex items-center gap-2 font-mono text-2xl font-bold tracking-wider"><MessageSquare className="h-6 w-6 shrink-0 text-primary" />{tr("贴吧", "MEMBER FORUM")}</h1><p className="mt-1 text-sm text-muted-foreground">{tr("军团成员的交流空间，分享内容、上传图片和文件。", "A space for corporation members to share posts, images and files.")}</p></div>{!isDetail && composer === null && <Button onClick={() => setComposer("new")}><Plus className="mr-2 h-4 w-4" />{tr("发帖", "New post")}</Button>}{isDetail && <Button asChild variant="outline"><Link href="/forum"><ArrowLeft className="mr-2 h-4 w-4" />{tr("返回贴吧", "Back to forum")}</Link></Button>}</div>
    {composer !== null && <ForumComposer key={composer === "new" ? "new" : composer.id} edit={composer === "new" ? undefined : composer} tr={tr} close={() => setComposer(null)} completed={(saved) => { void completed(saved); }} />}
    {!isDetail && <>
      <form className="flex min-w-0 gap-2" onSubmit={(event) => { event.preventDefault(); setPage(1); setQuery(queryInput.trim()); }}><Input aria-label={tr("搜索帖子", "Search posts")} value={queryInput} onChange={(event) => setQueryInput(event.target.value)} maxLength={100} placeholder={tr("搜索标题或内容", "Search titles or content")} className="min-w-0 flex-1" /><Button type="submit" variant="outline">{tr("搜索", "Search")}</Button></form>
      {list.isPending ? <div role="status" className="flex items-center gap-2 py-8 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />{tr("正在加载帖子……", "Loading posts…")}</div> : list.isError ? <QueryFailure error={list.error} retry={() => { void list.refetch(); }} tr={tr} /> : list.data && <>
        {list.data.posts.length === 0 ? <Card><CardContent className="py-10 text-center text-muted-foreground"><MessageSquare className="mx-auto mb-3 h-8 w-8" /><p>{query ? tr("没有找到相关帖子", "No matching posts") : tr("还没有帖子，来发布第一篇吧。", "No posts yet. Share the first one.")}</p></CardContent></Card> : <div className="space-y-3">{list.data.posts.map((item) => <Card key={item.id} className="min-w-0 transition-colors hover:border-primary/40"><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-center gap-2">{badges(item)}<Link href={`/forum/${item.id}`} className="min-w-0 break-words text-lg font-medium text-foreground hover:text-primary [overflow-wrap:anywhere]">{item.title}</Link></div><p className="line-clamp-2 whitespace-pre-wrap break-words text-sm text-muted-foreground [overflow-wrap:anywhere]">{item.body}</p><div className="flex flex-wrap gap-x-4 gap-y-1 break-words text-xs text-muted-foreground"><span className="[overflow-wrap:anywhere]">{item.author.name}</span><time dateTime={item.createdAt}>{date(item.createdAt)}</time><span className="flex items-center gap-1"><MessageSquare className="h-3 w-3" />{item.replyCount} {tr("回复", "replies")}</span>{item.attachments.length > 0 && <span className="flex items-center gap-1"><Paperclip className="h-3 w-3" />{item.attachments.length} {tr("附件", "attachments")}</span>}</div></CardContent></Card>)}</div>}
        <Pagination page={list.data.page} pageSize={list.data.pageSize} total={list.data.total} onChange={setPage} pending={list.isFetching} tr={tr} />
      </>}
    </>}
    {isDetail && (!Number.isSafeInteger(postId) || postId < 1) && <p role="alert">{tr("帖子编号无效。", "Invalid post ID.")}</p>}
    {isDetail && Number.isSafeInteger(postId) && postId > 0 && (detail.isPending ? <div role="status" className="flex gap-2 py-8"><Loader2 className="h-5 w-5 animate-spin" />{tr("正在加载帖子……", "Loading post…")}</div> : detail.isError ? <QueryFailure error={detail.error} retry={() => { void detail.refetch(); }} tr={tr} /> : post && detail.data && <>
      <Card className="min-w-0"><CardHeader className="space-y-3"><div className="flex flex-wrap gap-2">{badges(post)}</div><CardTitle role="heading" aria-level={2} className="break-words text-xl [overflow-wrap:anywhere]">{post.title}</CardTitle><CardDescription className="break-words [overflow-wrap:anywhere]">{post.author.name} · {date(post.createdAt)}{post.updatedAt !== post.createdAt && <span> · {tr("已编辑", "Edited")}</span>}</CardDescription><div className="flex flex-wrap gap-2">{post.canEdit && <Button variant="outline" size="sm" disabled={busy || composer !== null} onClick={() => setComposer(post)}><Pencil className="mr-2 h-3.5 w-3.5" />{tr("编辑", "Edit")}</Button>}{post.canDelete && <Button variant="outline" size="sm" disabled={busy} onClick={() => setConfirmation({ kind: "post", id: post.id })}><Trash2 className="mr-2 h-3.5 w-3.5" />{tr("删除帖子", "Delete post")}</Button>}{detail.data.canModerate && <><Button variant="outline" size="sm" disabled={busy} onClick={() => moderate.mutate({ pinned: !post.pinned })}><Pin className="mr-2 h-3.5 w-3.5" />{post.pinned ? tr("取消置顶", "Unpin") : tr("置顶", "Pin")}</Button><Button variant="outline" size="sm" disabled={busy} onClick={() => moderate.mutate({ locked: !post.locked })}><LockKeyhole className="mr-2 h-3.5 w-3.5" />{post.locked ? tr("解锁帖子", "Unlock") : tr("锁定帖子", "Lock")}</Button></>}</div></CardHeader><CardContent className="space-y-5"><p className="whitespace-pre-wrap break-words text-sm leading-7 [overflow-wrap:anywhere]">{post.body}</p><Attachments attachments={post.attachments} tr={tr} /></CardContent></Card>
      <div className="space-y-3"><h2 className="font-mono text-lg font-medium">{tr("回复", "Replies")} ({detail.data.replyTotal})</h2>{detail.data.replies.length === 0 && <p className="py-3 text-sm text-muted-foreground">{tr("暂无回复", "No replies yet")}</p>}{detail.data.replies.map((item) => <Card key={item.id}><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 text-xs text-muted-foreground [overflow-wrap:anywhere]">{item.author.name} · {date(item.createdAt)}{item.updatedAt !== item.createdAt && <span> · {tr("已编辑", "Edited")}</span>}</div><div className="flex gap-1">{item.canEdit && <Button size="sm" variant="ghost" disabled={busy} onClick={() => { setEditingReply(item); setReplyBody(item.body); setOperationError(null); document.getElementById("forum-reply")?.focus(); }}><Pencil className="mr-1 h-3.5 w-3.5" />{tr("编辑", "Edit")}</Button>}{item.canDelete && <Button size="sm" variant="ghost" disabled={busy} onClick={() => setConfirmation({ kind: "reply", id: item.id })}><Trash2 className="mr-1 h-3.5 w-3.5" />{tr("删除", "Delete")}</Button>}</div></div><p className="whitespace-pre-wrap break-words text-sm leading-6 [overflow-wrap:anywhere]">{item.body}</p></CardContent></Card>)}<Pagination page={detail.data.replyPage} pageSize={detail.data.replyPageSize} total={detail.data.replyTotal} onChange={setReplyPage} pending={detail.isFetching} tr={tr} /></div>
      {operationError && <p role="alert" className="break-words text-sm text-destructive">{operationError}</p>}
      {post.locked ? <div className="flex items-start gap-2 rounded-md border border-border bg-muted/20 p-4 text-sm text-muted-foreground"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />{tr("帖子已锁定，暂时不能回复或编辑内容。", "This post is locked. Replies and edits are disabled.")}</div> : <Card><CardHeader><CardTitle className="text-base">{editingReply ? tr("编辑回复", "Edit reply") : tr("发表回复", "Write a reply")}</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); if (!busy && replyBody.trim()) reply.mutate(); }}><Label className="sr-only" htmlFor="forum-reply">{tr("回复内容", "Reply content")}</Label><Textarea id="forum-reply" rows={4} maxLength={forumLimits.bodyMax} value={replyBody} disabled={busy} onChange={(event) => setReplyBody(event.target.value)} placeholder={tr("写下你的回复……", "Write your reply…")} /><p className="text-right text-xs text-muted-foreground">{replyBody.length} / {forumLimits.bodyMax}</p><div className="flex flex-wrap justify-end gap-2">{editingReply && <Button type="button" variant="outline" disabled={busy} onClick={() => { setEditingReply(null); setReplyBody(""); }}>{tr("取消编辑", "Cancel edit")}</Button>}<Button type="submit" disabled={busy || !replyBody.trim()}>{reply.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{editingReply ? tr("保存回复", "Save reply") : tr("发表回复", "Reply")}</Button></div></form></CardContent></Card>}
    </>)}
    <AlertDialog open={confirmation !== null} onOpenChange={(open) => { if (!open && !remove.isPending) setConfirmation(null); }}><AlertDialogContent className="max-w-[calc(100%-2rem)] sm:max-w-lg"><AlertDialogHeader><AlertDialogTitle>{tr("确认删除？", "Delete this content?")}</AlertDialogTitle><AlertDialogDescription>{confirmation?.kind === "post" ? tr("删除后，帖子、回复和附件将不再对成员可见。", "The post, replies and attachments will no longer be visible to members.") : tr("删除后，这条回复将不再可见。", "This reply will no longer be visible.")}</AlertDialogDescription></AlertDialogHeader>{remove.isError && <p role="alert" className="break-words text-sm text-destructive">{getErrorMessage(remove.error)}</p>}<AlertDialogFooter><AlertDialogCancel disabled={remove.isPending}>{tr("取消", "Cancel")}</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={remove.isPending} onClick={(event) => { event.preventDefault(); if (confirmation && !remove.isPending) remove.mutate(confirmation); }}>{remove.isPending ? tr("删除中……", "Deleting…") : tr("删除", "Delete")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
