import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import charactersRouter from "./characters";
import fleetsRouter from "./fleets";
import papRouter from "./pap";
import rewardsRouter from "./rewards";
import redemptionsRouter from "./redemptions";
import dashboardRouter from "./dashboard";
import announcementsRouter from "./announcements";
import battleReportsRouter from "./battle-reports";
import battleReplaysRouter from "./battle-replays";
import fittingRouter from "./fitting";
import identityGroupsRouter from "./identity-groups";
import diplomacyRouter from "./diplomacy";
import reimbursementsRouter from "./reimbursements";
import economyRouter from "./economy";
import activityRouter from "./activity";
import tacticalGroupsRouter from "./tactical-groups";
import courierRouter from "./courier";
import structuresRouter from "./structures";
import papMarketRouter from "./pap-market";
import systemMonitoringRouter from "./system-monitoring";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(charactersRouter);
router.use(fleetsRouter);
router.use(papRouter);
router.use(rewardsRouter);
router.use(redemptionsRouter);
router.use(dashboardRouter);
router.use(announcementsRouter);
router.use(battleReportsRouter);
router.use(battleReplaysRouter);
router.use(fittingRouter);
router.use(identityGroupsRouter);
router.use(diplomacyRouter);
router.use(reimbursementsRouter);
router.use(economyRouter);
router.use(activityRouter);
router.use(tacticalGroupsRouter);
router.use(courierRouter);
router.use(structuresRouter);
router.use(papMarketRouter);
router.use(systemMonitoringRouter);

export default router;
